// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbq

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (id, type, hash, source, options, request_fingerprint, status, callback_url, retry_of_job_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateJobParams struct {
	ID                 string          `json:"id"`
	Type               string          `json:"type"`
	Hash               string          `json:"hash"`
	Source             string          `json:"source"`
	Options            json.RawMessage `json:"options"`
	RequestFingerprint string          `json:"request_fingerprint"`
	Status             string          `json:"status"`
	CallbackUrl        string          `json:"callback_url"`
	RetryOfJobID       pgtype.Text     `json:"retry_of_job_id"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.Exec(ctx, createJob,
		arg.ID,
		arg.Type,
		arg.Hash,
		arg.Source,
		arg.Options,
		arg.RequestFingerprint,
		arg.Status,
		arg.CallbackUrl,
		arg.RetryOfJobID,
	)
	return err
}

const deleteJobsByHash = `-- name: DeleteJobsByHash :exec
DELETE FROM jobs WHERE hash = $1
`

func (q *Queries) DeleteJobsByHash(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteJobsByHash, hash)
	return err
}

const getActiveJobByFingerprint = `-- name: GetActiveJobByFingerprint :one
SELECT id, type, hash, source, options, request_fingerprint, status, progress, callback_url, callback_status, retry_of_job_id, error, results, created_at, updated_at FROM jobs
WHERE request_fingerprint = $1 AND status NOT IN ('failed', 'cancelled')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveJobByFingerprint(ctx context.Context, requestFingerprint string) (Job, error) {
	row := q.db.QueryRow(ctx, getActiveJobByFingerprint, requestFingerprint)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Hash,
		&i.Source,
		&i.Options,
		&i.RequestFingerprint,
		&i.Status,
		&i.Progress,
		&i.CallbackUrl,
		&i.CallbackStatus,
		&i.RetryOfJobID,
		&i.Error,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, hash, source, options, request_fingerprint, status, progress, callback_url, callback_status, retry_of_job_id, error, results, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Hash,
		&i.Source,
		&i.Options,
		&i.RequestFingerprint,
		&i.Status,
		&i.Progress,
		&i.CallbackUrl,
		&i.CallbackStatus,
		&i.RetryOfJobID,
		&i.Error,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobsByHash = `-- name: ListJobsByHash :many
SELECT id, type, hash, source, options, request_fingerprint, status, progress, callback_url, callback_status, retry_of_job_id, error, results, created_at, updated_at FROM jobs WHERE hash = $1 ORDER BY created_at
`

func (q *Queries) ListJobsByHash(ctx context.Context, hash string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByHash, hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Hash,
			&i.Source,
			&i.Options,
			&i.RequestFingerprint,
			&i.Status,
			&i.Progress,
			&i.CallbackUrl,
			&i.CallbackStatus,
			&i.RetryOfJobID,
			&i.Error,
			&i.Results,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetryJobs = `-- name: ListRetryJobs :many
SELECT id, type, hash, source, options, request_fingerprint, status, progress, callback_url, callback_status, retry_of_job_id, error, results, created_at, updated_at FROM jobs WHERE retry_of_job_id = $1 ORDER BY created_at
`

func (q *Queries) ListRetryJobs(ctx context.Context, retryOfJobID pgtype.Text) ([]Job, error) {
	rows, err := q.db.Query(ctx, listRetryJobs, retryOfJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Hash,
			&i.Source,
			&i.Options,
			&i.RequestFingerprint,
			&i.Status,
			&i.Progress,
			&i.CallbackUrl,
			&i.CallbackStatus,
			&i.RetryOfJobID,
			&i.Error,
			&i.Results,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCallbackStatus = `-- name: UpdateCallbackStatus :exec
UPDATE jobs SET callback_status = $2 WHERE id = $1
`

type UpdateCallbackStatusParams struct {
	ID             string `json:"id"`
	CallbackStatus string `json:"callback_status"`
}

func (q *Queries) UpdateCallbackStatus(ctx context.Context, arg UpdateCallbackStatusParams) error {
	_, err := q.db.Exec(ctx, updateCallbackStatus, arg.ID, arg.CallbackStatus)
	return err
}

const updateJobCompletion = `-- name: UpdateJobCompletion :exec
UPDATE jobs SET status = 'completed', progress = 100, error = NULL, results = $2 WHERE id = $1
`

type UpdateJobCompletionParams struct {
	ID      string          `json:"id"`
	Results json.RawMessage `json:"results"`
}

func (q *Queries) UpdateJobCompletion(ctx context.Context, arg UpdateJobCompletionParams) error {
	_, err := q.db.Exec(ctx, updateJobCompletion, arg.ID, arg.Results)
	return err
}

const updateJobFailure = `-- name: UpdateJobFailure :exec
UPDATE jobs SET status = 'failed', error = $2, results = $3 WHERE id = $1
`

type UpdateJobFailureParams struct {
	ID      string          `json:"id"`
	Error   pgtype.Text     `json:"error"`
	Results json.RawMessage `json:"results"`
}

func (q *Queries) UpdateJobFailure(ctx context.Context, arg UpdateJobFailureParams) error {
	_, err := q.db.Exec(ctx, updateJobFailure, arg.ID, arg.Error, arg.Results)
	return err
}

const updateJobProgress = `-- name: UpdateJobProgress :exec
UPDATE jobs SET progress = $2 WHERE id = $1
`

type UpdateJobProgressParams struct {
	ID       string `json:"id"`
	Progress int32  `json:"progress"`
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateJobProgress, arg.ID, arg.Progress)
	return err
}

const updateJobResults = `-- name: UpdateJobResults :exec
UPDATE jobs SET results = $2 WHERE id = $1
`

type UpdateJobResultsParams struct {
	ID      string          `json:"id"`
	Results json.RawMessage `json:"results"`
}

func (q *Queries) UpdateJobResults(ctx context.Context, arg UpdateJobResultsParams) error {
	_, err := q.db.Exec(ctx, updateJobResults, arg.ID, arg.Results)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs SET status = $2, error = $3 WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID     string      `json:"id"`
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus, arg.ID, arg.Status, arg.Error)
	return err
}
