// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: keys.sql

package dbq

import (
	"context"
)

const deleteEncryptionKey = `-- name: DeleteEncryptionKey :exec
DELETE FROM encryption_keys WHERE hash = $1
`

func (q *Queries) DeleteEncryptionKey(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteEncryptionKey, hash)
	return err
}

const deleteImageCacheEntriesByHash = `-- name: DeleteImageCacheEntriesByHash :exec
DELETE FROM image_cache_entries WHERE hash = $1
`

func (q *Queries) DeleteImageCacheEntriesByHash(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteImageCacheEntriesByHash, hash)
	return err
}

const getEncryptionKey = `-- name: GetEncryptionKey :one
SELECT hash, wrapped_key, wrap_nonce, kek_version, kid, scheme, key_uri, created_at FROM encryption_keys WHERE hash = $1
`

func (q *Queries) GetEncryptionKey(ctx context.Context, hash string) (EncryptionKey, error) {
	row := q.db.QueryRow(ctx, getEncryptionKey, hash)
	var i EncryptionKey
	err := row.Scan(
		&i.Hash,
		&i.WrappedKey,
		&i.WrapNonce,
		&i.KekVersion,
		&i.Kid,
		&i.Scheme,
		&i.KeyUri,
		&i.CreatedAt,
	)
	return i, err
}

const listImageCacheEntriesByHash = `-- name: ListImageCacheEntriesByHash :many
SELECT hash, cache_key, storage_key, created_at FROM image_cache_entries WHERE hash = $1 ORDER BY created_at
`

func (q *Queries) ListImageCacheEntriesByHash(ctx context.Context, hash string) ([]ImageCacheEntry, error) {
	rows, err := q.db.Query(ctx, listImageCacheEntriesByHash, hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageCacheEntry{}
	for rows.Next() {
		var i ImageCacheEntry
		if err := rows.Scan(
			&i.Hash,
			&i.CacheKey,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEncryptionKey = `-- name: UpsertEncryptionKey :exec
INSERT INTO encryption_keys (hash, wrapped_key, wrap_nonce, kek_version, kid, scheme, key_uri)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (hash) DO UPDATE SET
	wrapped_key = EXCLUDED.wrapped_key,
	wrap_nonce = EXCLUDED.wrap_nonce,
	kek_version = EXCLUDED.kek_version,
	kid = EXCLUDED.kid,
	scheme = EXCLUDED.scheme,
	key_uri = EXCLUDED.key_uri
`

type UpsertEncryptionKeyParams struct {
	Hash       string `json:"hash"`
	WrappedKey []byte `json:"wrapped_key"`
	WrapNonce  []byte `json:"wrap_nonce"`
	KekVersion string `json:"kek_version"`
	Kid        string `json:"kid"`
	Scheme     string `json:"scheme"`
	KeyUri     string `json:"key_uri"`
}

func (q *Queries) UpsertEncryptionKey(ctx context.Context, arg UpsertEncryptionKeyParams) error {
	_, err := q.db.Exec(ctx, upsertEncryptionKey,
		arg.Hash,
		arg.WrappedKey,
		arg.WrapNonce,
		arg.KekVersion,
		arg.Kid,
		arg.Scheme,
		arg.KeyUri,
	)
	return err
}

const upsertImageCacheEntry = `-- name: UpsertImageCacheEntry :exec
INSERT INTO image_cache_entries (hash, cache_key, storage_key)
VALUES ($1, $2, $3)
ON CONFLICT (hash, storage_key) DO UPDATE SET
	cache_key = EXCLUDED.cache_key,
	created_at = now()
`

type UpsertImageCacheEntryParams struct {
	Hash       string `json:"hash"`
	CacheKey   string `json:"cache_key"`
	StorageKey string `json:"storage_key"`
}

func (q *Queries) UpsertImageCacheEntry(ctx context.Context, arg UpsertImageCacheEntryParams) error {
	_, err := q.db.Exec(ctx, upsertImageCacheEntry, arg.Hash, arg.CacheKey, arg.StorageKey)
	return err
}
