// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lifecycle.sql

package dbq

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceMediaCacheAudit = `-- name: AdvanceMediaCacheAudit :exec
UPDATE media_lifecycle_readiness
SET cache_audit_cursor = $1,
    updated_at = now()
WHERE singleton = TRUE
  AND cache_audit_complete = FALSE
  AND cache_audit_armed = TRUE
  AND cache_audit_error = ''
`

func (q *Queries) AdvanceMediaCacheAudit(ctx context.Context, cacheAuditCursor string) error {
	_, err := q.db.Exec(ctx, advanceMediaCacheAudit, cacheAuditCursor)
	return err
}

const bindMediaDeploymentTarget = `-- name: BindMediaDeploymentTarget :execrows
UPDATE media_lifecycle_readiness
SET protocol_version = $1,
    deployment_id = $2,
    source_backend_identity = $3,
    media_backend_identity = $4,
    updated_at = now()
WHERE singleton = TRUE
  AND protocol_version IS NULL
  AND deployment_id IS NULL
  AND source_backend_identity IS NULL
  AND media_backend_identity IS NULL
`

type BindMediaDeploymentTargetParams struct {
	ProtocolVersion       pgtype.Int2 `json:"protocol_version"`
	DeploymentID          pgtype.Text `json:"deployment_id"`
	SourceBackendIdentity pgtype.Text `json:"source_backend_identity"`
	MediaBackendIdentity  pgtype.Text `json:"media_backend_identity"`
}

func (q *Queries) BindMediaDeploymentTarget(ctx context.Context, arg BindMediaDeploymentTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindMediaDeploymentTarget,
		arg.ProtocolVersion,
		arg.DeploymentID,
		arg.SourceBackendIdentity,
		arg.MediaBackendIdentity,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeMediaCacheAudit = `-- name: CompleteMediaCacheAudit :exec
UPDATE media_lifecycle_readiness
SET cache_audit_complete = TRUE,
    cache_audit_error = '',
    updated_at = now()
WHERE singleton = TRUE
  AND cache_audit_armed = TRUE
`

func (q *Queries) CompleteMediaCacheAudit(ctx context.Context) error {
	_, err := q.db.Exec(ctx, completeMediaCacheAudit)
	return err
}

const createMediaTombstone = `-- name: CreateMediaTombstone :exec
INSERT INTO media_tombstones (hash, source)
VALUES ($1, $2)
ON CONFLICT (hash, source) DO NOTHING
`

type CreateMediaTombstoneParams struct {
	Hash   string `json:"hash"`
	Source string `json:"source"`
}

func (q *Queries) CreateMediaTombstone(ctx context.Context, arg CreateMediaTombstoneParams) error {
	_, err := q.db.Exec(ctx, createMediaTombstone, arg.Hash, arg.Source)
	return err
}

const failMediaCacheAudit = `-- name: FailMediaCacheAudit :exec
UPDATE media_lifecycle_readiness
SET cache_audit_error = $1,
    updated_at = now()
WHERE singleton = TRUE
  AND cache_audit_armed = TRUE
`

func (q *Queries) FailMediaCacheAudit(ctx context.Context, cacheAuditError string) error {
	_, err := q.db.Exec(ctx, failMediaCacheAudit, cacheAuditError)
	return err
}

const getMediaDeploymentTarget = `-- name: GetMediaDeploymentTarget :one
SELECT COALESCE(protocol_version, 0)::smallint AS protocol_version,
       COALESCE(deployment_id, '')::text AS deployment_id,
       COALESCE(source_backend_identity, '')::text AS source_backend_identity,
       COALESCE(media_backend_identity, '')::text AS media_backend_identity
FROM media_lifecycle_readiness
WHERE singleton = TRUE
`

type GetMediaDeploymentTargetRow struct {
	ProtocolVersion       int16  `json:"protocol_version"`
	DeploymentID          string `json:"deployment_id"`
	SourceBackendIdentity string `json:"source_backend_identity"`
	MediaBackendIdentity  string `json:"media_backend_identity"`
}

func (q *Queries) GetMediaDeploymentTarget(ctx context.Context) (GetMediaDeploymentTargetRow, error) {
	row := q.db.QueryRow(ctx, getMediaDeploymentTarget)
	var i GetMediaDeploymentTargetRow
	err := row.Scan(
		&i.ProtocolVersion,
		&i.DeploymentID,
		&i.SourceBackendIdentity,
		&i.MediaBackendIdentity,
	)
	return i, err
}

const getMediaLifecycleReadiness = `-- name: GetMediaLifecycleReadiness :one
SELECT singleton, cache_audit_armed, cache_audit_cursor, cache_audit_complete, cache_audit_error, updated_at
FROM media_lifecycle_readiness
WHERE singleton = TRUE
`

type GetMediaLifecycleReadinessRow struct {
	Singleton          bool      `json:"singleton"`
	CacheAuditArmed    bool      `json:"cache_audit_armed"`
	CacheAuditCursor   string    `json:"cache_audit_cursor"`
	CacheAuditComplete bool      `json:"cache_audit_complete"`
	CacheAuditError    string    `json:"cache_audit_error"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) GetMediaLifecycleReadiness(ctx context.Context) (GetMediaLifecycleReadinessRow, error) {
	row := q.db.QueryRow(ctx, getMediaLifecycleReadiness)
	var i GetMediaLifecycleReadinessRow
	err := row.Scan(
		&i.Singleton,
		&i.CacheAuditArmed,
		&i.CacheAuditCursor,
		&i.CacheAuditComplete,
		&i.CacheAuditError,
		&i.UpdatedAt,
	)
	return i, err
}

const isMediaTombstoned = `-- name: IsMediaTombstoned :one
SELECT EXISTS (
    SELECT 1 FROM media_tombstones WHERE hash = $1 AND source = $2
)
`

type IsMediaTombstonedParams struct {
	Hash   string `json:"hash"`
	Source string `json:"source"`
}

func (q *Queries) IsMediaTombstoned(ctx context.Context, arg IsMediaTombstonedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMediaTombstoned, arg.Hash, arg.Source)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
