// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type ImageCacheEntry struct {
	Hash       string    `json:"hash"`
	CacheKey   string    `json:"cache_key"`
	StorageKey string    `json:"storage_key"`
	CreatedAt  time.Time `json:"created_at"`
}

type Job struct {
	ID                 string          `json:"id"`
	Type               string          `json:"type"`
	Hash               string          `json:"hash"`
	Source             string          `json:"source"`
	Options            json.RawMessage `json:"options"`
	RequestFingerprint string          `json:"request_fingerprint"`
	Status             string          `json:"status"`
	Progress           int32           `json:"progress"`
	CallbackUrl        string          `json:"callback_url"`
	CallbackStatus     string          `json:"callback_status"`
	RetryOfJobID       pgtype.Text     `json:"retry_of_job_id"`
	Error              pgtype.Text     `json:"error"`
	Results            json.RawMessage `json:"results"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type StreamEncryptionKey struct {
	ID            uuid.UUID `json:"id"`
	SourceHash    string    `json:"source_hash"`
	AssetType     string    `json:"asset_type"`
	PackagingType string    `json:"packaging_type"`
	WrappedKey    []byte    `json:"wrapped_key"`
	WrapNonce     []byte    `json:"wrap_nonce"`
	KekVersion    string    `json:"kek_version"`
	Kid           string    `json:"kid"`
	Scheme        string    `json:"scheme"`
	CreatedAt     time.Time `json:"created_at"`
}
