version: "2"
linters:
  enable:
    - bodyclose
    - gocritic
    - misspell
    - nilerr
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-tags:
        - style
        - experimental
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - gocritic
          - unused
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - Vylux
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
